### ISSUE TITLE
tpfancod-packaging issues

### ISSUE THREAD

**Issue by Ryushin** [tpfanco/tpfancod-packaging#1]
Copied the debian directory into the git clone of tpfancod.

Building package with: dpkg-buildpackage -b -uc -uc

Error: cp: cannot stat 'README': No such file or directory
copied README.MD to README.

Compiled again: dpkg-buildpackage -b -uc -uc
Error: tpfand.8: No such file or directory at /usr/bin/dh_installman line 131.

At this point I stopped trying to compile a debian package and will just compile the source directly.  I have not tested the other two packaging tpfanco-admin-packaging or tpfancod-profiles-packaging.

**Comment by vsht** [comment]
Frankly speaking, I stopped using Debian based distributions several years ago, so the packaging is indeed in a very bad state. Unfortunately, I don't have time to go through all the packaging regulations and I also think that this is something that should be done by a person with some experience in this field. So if someone want to help package tpfanco & co for different distributions, I'll gladly accept the corresponding pull requests.
